sudo: requiered # superuser level permissions
language: generic

services:
  - docker


before_install:
  - docker build -t michaeloc/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true michaeloc/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-new"
  env: "Dockerreactnew-env" 
  bucket_name: "elasticbeanstalk-us-east-1-328902822644"
  bucket_path: "docker-react-new"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"